apiVersion: v1
kind: Service
metadata:
  name:  web-app
  namespace: dev-afiatan
spec:
  selector:
    app: web-app
  ports:
  - protocol: TCP
    port: 12480
    targetPort: 12480
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: dev-bssn2024
  labels:
    app: web-app
spec:
  strategy:
      type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      imagePullSecrets:
      - name: regkano
      containers:
      - name: web-app
        image: registry.kanosolution.net/bssn2024/web/web:dev.deploy
        imagePullPolicy: Always
        ports:
        - containerPort: 12480