 variables:
  V_BUILD_MODE: dev
  V_DEVOPS_DOCKER: devops/$V_BUILD_MODE/Dockerfile
  V_DEVOPS_K8S: devops/$V_BUILD_MODE/k8.yml
 
 build:web:
  stage: build
  dependencies: []
  only:
    - /\.deploy$/
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - |
      /kaniko/executor --context $CI_PROJECT_DIR \
        --dockerfile $CI_PROJECT_DIR/$V_DEVOPS_DOCKER \
        --build-arg BuildMode=$V_BUILD_MODE \
        --build-arg GitUser=gitlab-ci-token \
        --build-arg GitSecret=${CI_JOB_TOKEN} \
        --build-arg AppName=$APP_NAME \
        --build-arg GitSecret=${CI_JOB_TOKEN} \
        --destination $CI_REGISTRY_IMAGE/web-app:$V_BUILD_MODE